<a href="https://colab.research.google.com/github/iBoukhenna/ai-masterclass/blob/ml/Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy - Numerical Python

#Advantages of Numpy Arrays


1.   Allows several Mathematical Operations
2.   Faster operations



In [1]:
import numpy as np

#List vs Numpy - Time Taken

In [3]:
from time import process_time

#Time taken by a list

In [4]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in range(10000)]
end_time = process_time()
print(end_time - start_time)

0.0016818719999998066


#Time taken by Numpy array

In [6]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.0007356740000012962


#Numpy Arrays

In [7]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
# creating a 1 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
b.shape

(2, 4)

In [13]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#Initial Placeholders in numpy arrays

In [15]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
# create a numpy array of Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.57564498 0.04284153 0.96868784 0.47669354]
 [0.03504346 0.01291705 0.08624055 0.42123894]
 [0.47304836 0.81651396 0.57989226 0.01038833]]


In [21]:
# random integer values array within a specific
c = np.random.randint(10,100, (3,5))
print(c)

[[76 40 61 87 77]
 [63 52 34 15 58]
 [60 61 84 78 12]]


In [23]:
# array of evenly spaced values specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [24]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [25]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

#Analysing a numpy array

In [26]:
c = np.random.randint(10,90,(5,5))
print(c)

[[58 55 89 21 75]
 [57 44 69 50 12]
 [52 17 19 27 27]
 [42 11 69 13 11]
 [86 30 36 27 53]]


In [27]:
# array dimension
print(c.shape)

(5, 5)


In [28]:
# number of dimensions
print(c.ndim)

2


In [29]:
# number of elements in an array
print(c.size)

25


In [30]:
# checking the data ype of the values in the array
print(c.dtype)

int64


#Mathematical operations on a np array

In [31]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

# concatenate or joins two list
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [36]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 5 5]
 [8 9 4]
 [8 7 6]]
[[13 17 19]
 [19 11 16]
 [12 18 12]]


In [37]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[18 22 24]
 [27 20 20]
 [20 25 18]]
[[ -8 -12 -14]
 [-11  -2 -12]
 [ -4 -11  -6]]
[[ 65  85  95]
 [152  99  64]
 [ 96 126  72]]
[[0.38461538 0.29411765 0.26315789]
 [0.42105263 0.81818182 0.25      ]
 [0.66666667 0.38888889 0.5       ]]


In [39]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[6 1 7]
 [5 5 9]
 [1 6 0]]
[[19 15 13]
 [16 10 10]
 [19 18 16]]
[[25 16 20]
 [21 15 19]
 [20 24 16]]
[[-13 -14  -6]
 [-11  -5  -1]
 [-18 -12 -16]]
[[114  15  91]
 [ 80  50  90]
 [ 19 108   0]]
[[0.31578947 0.06666667 0.53846154]
 [0.3125     0.5        0.9       ]
 [0.05263158 0.33333333 0.        ]]


#Array Manipulation

In [42]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 8 9]
 [2 8 2]]
(2, 3)


In [43]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 2]
 [8 8]
 [9 2]]
(3, 2)


In [44]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 3 0]
 [2 3 6]]
(2, 3)


In [45]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[6 2]
 [3 3]
 [0 6]]
(3, 2)


In [47]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 7 2]
 [8 3 8]]
(2, 3)


In [49]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 7]
 [2 8]
 [3 8]]
(3, 2)
