<a href="https://colab.research.google.com/github/iBoukhenna/ai-masterclass/blob/ml/5_1_7_Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Creating a Matrix using numpy

In [4]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [7]:
matrix_2.shape

(3, 3)

#Creating Matrices with Random Values

In [8]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.16187708 0.834943   0.25199784]
 [0.77005602 0.0928671  0.34582833]
 [0.02121614 0.77953964 0.51287829]]


In [10]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[98 25 16 17 80]
 [85 50 99 46 49]
 [ 0 28 60 78 37]
 [92  5 31  8 27]]


#Matrix with all the values as 1

In [12]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [16]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


#Null Matrix or Zero Matrix

In [17]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#Identity Matrix

In [19]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#Transpose of a Matrix

In [21]:
# matrix with random integer value
a = np.random.randint(100, size=(4,5))
print(a)

[[83 35 35 32  5]
 [27 52 78 56  2]
 [90 45 48 30 51]
 [10  1 35 28 26]]


In [22]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[83 27 90 10]
 [35 52 45  1]
 [35 78 48 35]
 [32 56 30 28]
 [ 5  2 51 26]]
