<a href="https://colab.research.google.com/github/iBoukhenna/ai-masterclass/blob/ml/5_1_9_Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importing Numpy Library

In [2]:
import numpy as np

#Matrix Addition
Two matrices can be added only if they have the same shape

In [3]:
# creating two matrices
A = np.array([[2,3],[10,5]])
B = np.array([[10,5],[20,4]])

In [5]:
print(A)

[[ 2  3]
 [10  5]]


In [6]:
print(B)

[[10  5]
 [20  4]]


In [7]:
A.shape

(2, 2)

In [8]:
B.shape

(2, 2)

#Adding two Matrices

In [9]:
sum = A + B

In [10]:
print(sum)

[[12  8]
 [30  9]]


In [18]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [19]:
print(matrix_1)

[[5 1 0]
 [1 5 3]
 [7 4 5]]


In [20]:
print(matrix_2)

[[14  2  0]
 [ 1  4 14]
 [ 6  4 13]]


In [21]:
sum = np.add(matrix_1, matrix_2)

In [22]:
print(sum)

[[19  3  0]
 [ 2  9 17]
 [13  8 18]]


In [23]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [24]:
# sum_2 = np.add(matrix_3,matrix_4)
# we get error because shape of matrix_3 and matrix_4 are different

#Martix Subtraction

In [25]:
diff = A - B

In [26]:
print(diff)

[[ -8  -2]
 [-10   1]]


In [27]:
diff = np.subtract(matrix_1, matrix_2)

In [28]:
print(diff)

[[ -9  -1   0]
 [  0   1 -11]
 [  1   0  -8]]


In [29]:
# diff_2 = np.subtract(matrix_3,matrix_4)
# we get error because shape of matrix_3 and matrix_4 are different

#Multiplying a Martix by Scalar

In [30]:
x = 5
y = np.array([[2,1],[4,2],[6,3]])

In [31]:
print(y)

[[2 1]
 [4 2]
 [6 3]]


In [33]:
product = x * y

In [34]:
print(product)

[[10  5]
 [20 10]
 [30 15]]


In [37]:
w = 10
z = np.random.randint(10, size=(4,4))

In [38]:
print(z)

[[5 6 7 7]
 [2 4 5 2]
 [0 2 8 2]
 [0 1 5 7]]


In [39]:
product = np.multiply(w, z)

In [40]:
print(product)

[[50 60 70 70]
 [20 40 50 20]
 [ 0 20 80 20]
 [ 0 10 50 70]]


#Multiplying 2 Martices

In [46]:
E = np.array([[2,3],[8,6]])
F = np.array([[10,5],[20,4]])

In [47]:
print(E)

[[2 3]
 [8 6]]


In [48]:
print(F)

[[10  5]
 [20  4]]


In [54]:
product = np.dot(E, F)
product2 = E * F

In [55]:
print(product)

[[ 80  22]
 [200  64]]


In [56]:
print(product2)

[[ 20  15]
 [160  24]]


np.dot is different than *

In [63]:
# create two matrices with random values
matrix_5 = np.random.randint(5, size=(3,3))
matrix_6 = np.random.randint(5, size=(3,4))

In [64]:
print(matrix_5)

[[3 4 2]
 [4 0 0]
 [3 0 3]]


In [65]:
print(matrix_6)

[[2 0 0 4]
 [3 1 0 4]
 [0 1 4 3]]


In [66]:
product = np.dot(matrix_5, matrix_6)

In [67]:
print(product)

[[18  6  8 34]
 [ 8  0  0 16]
 [ 6  3 12 21]]


In [68]:
# create two matrices with random values
matrix_7 = np.random.randint(5, size=(3,3))
matrix_8 = np.random.randint(5, size=(4,4))

In [69]:
# product = np.dot(matrix_7, matrix_8)
# we get error because numbre of columns of matrix_7 and number of rows of matrix_8 are different

#Element wise matrix multiplication

In [70]:
product = np.multiply(E, F)
product2 = E * F

In [71]:
print(product)

[[ 20  15]
 [160  24]]


In [72]:
print(product2)

[[ 20  15]
 [160  24]]


np.multiply is equal than *

In [73]:
# product = np.multiply(matrix_7, matrix_8)
# we get error because shape of matrix_7 and matrix_8 are different